### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by ietda** [cssxsh/mirai-openai-plugin#12]
```
2023-03-03 13:08:10 W/MiraiOpenAiListener: MiraiOpenAiListener with GroupMessageEvent(group=********, senderName=******, sender=*********, permission=OWNER, message=[mirai:source:ids=[36262], internalIds=[454837387], from group ******** to ******** at ******]chat)
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at mirai-openai-plugin-1.1.0.mirai2.jar[private]//okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
已经试过更换api、下载旧版本插件，依然报错

**Comment by byzp** [comment]
疑似api被墙，昨天我也预到了这个问题。

**Comment by byzp** [comment]
疑似api被墙，昨天我也遇到了这个问题。

**Comment by cssxsh** [comment]
`api.openai.com` 已经列入黑名单，你需要配置代理

**Comment by ietda** [comment]
> `api.openai.com` 已经列入黑名单，你需要配置代理

谢谢

**Comment by ietda** [comment]
> 疑似api被墙，昨天我也遇到了这个问题。

谢谢
