### ISSUE TITLE
[Bug Report] 更新1.2.0后聊天报错message is empty

### ISSUE THREAD

**Issue by chenxi050402** [cssxsh/mirai-openai-plugin#14]
```
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:258)
        at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:102)
        at mirai-openai-plugin-1.2.0.mirai2.jar//xyz.cssxsh.mirai.openai.MiraiOpenAiListener$chat$4$2.invokeSuspend(MiraiOpenAiListener.kt:206)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-openai-plugin/releases/tag/v1.2.1
