### ISSUE TITLE
使用问答模型出现了以下报错

### ISSUE THREAD

**Issue by lian-koishi** [cssxsh/mirai-openai-plugin#30]
**如图，群聊中测试使用问答模型后输出不完整**
![image](https://user-images.githubusercontent.com/105502146/230735726-77eaf38d-785d-4297-8e81-2fd86ed1f4e3.png)
**这是后台报错代码：**
```
2023-04-09 01:45:22 V/Bot.1639275564: [后台ai线报测试群(273068320)] 空恋(1839275564) -> ?
2023-04-09 01:45:22 W/MiraiOpenAiListener: MiraiOpenAiListener with GroupMessageEvent(group=273068320, senderName=空恋, sender=1839275564, permission=OWNER, message=[mirai:source:ids=[52253], internalIds=[1386621445], from group 1839275564 to 273068320 at 1680975870]蓝白我需要你的帮助！)
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:258)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:219)
        at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
        at mirai-openai-plugin-1.4.2.mirai2.jar//xyz.cssxsh.mirai.openai.MiraiOpenAiListener$question$6$2.invokeSuspend(MiraiOpenAiListener.kt:343)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
**请问一下我该如何解决该报错？**

**Comment by cssxsh** [comment]
> message is empty
