### ISSUE TITLE
从actions里面下载的最新那个8d829bf 版本 报OpenAI API 异常, ErrorInfo(code=null, message="[] is too short - 'tools'", param=null, type=invalid_request_error)

### ISSUE THREAD

**Issue by fufuzhou** [cssxsh/mirai-openai-plugin#43]
2023-11-08 14:29:34 V/Bot.: &() -> 来聊
2023-11-08 14:29:35 W/MiraiOpenAiListener: MiraiOpenAiListener with FriendMessageEvent(sender=, message=[mirai:source:ids=[4883], internalIds=[1404953672], from friend to at 1699424974]来聊)
xyz.cssxsh.openai.OpenAiException: ErrorInfo(code=null, message="[] is too short - 'tools'", param=null, type=invalid_request_error)
	at mirai-openai-plugin-1.5.1.mirai2.jar//xyz.cssxsh.openai.OpenAiClient$http$1$4$1.invokeSuspend(OpenAiClient.kt:60)
	at mirai-openai-plugin-1.5.1.mirai2.jar//xyz.cssxsh.openai.OpenAiClient$http$1$4$1.invoke(OpenAiClient.kt)
	at mirai-openai-plugin-1.5.1.mirai2.jar//xyz.cssxsh.openai.OpenAiClient$http$1$4$1.invoke(OpenAiClient.kt)
	at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
	at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
	at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-11-08 14:29:36 V/Bot.: Friend() <- [mirai:quote:[mirai:source:ids=[4883], internalIds=[1404953672], from friend to at 1699424974], content=来聊]OpenAI API 异常, ErrorInfo(code=null, message="[] is too short - 'tools'", param=null, type=invalid_request_error)

**Comment by cssxsh** [comment]
起标题的能力有待加强
