### ISSUE TITLE
在使用V1.5.1+新模型时出现的问题

### ISSUE THREAD

**Issue by Hammerstein3217** [cssxsh/mirai-openai-plugin#48]
```java
io.ktor.serialization.JsonConvertException: Illegal input
        at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:79)       
        at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter$deserialize$1.invokeSuspend(KotlinxSerializationConverter.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 404: Encountered an unknown key 'system_fingerprint' at path: $.usage
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....   "total_tokens": 38
  },
  "system_fingerprint": null
}

        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:579)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:251)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:237)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:172)
        at mirai-openai-plugin-1.5.1.mirai2.jar//xyz.cssxsh.openai.chat.ChatInfo$$serializer.deserialize(ChatInfo.kt:6)
        at mirai-openai-plugin-1.5.1.mirai2.jar//xyz.cssxsh.openai.chat.ChatInfo$$serializer.deserialize(ChatInfo.kt:6)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
        at mirai-openai-plugin-1.5.1.mirai2.jar[private]//io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:71)        
        ... 7 more
``` 
报错内容如上
此前1.2.1版本好像能正常使用（因为一直没更新）
尝试换GPT4的时候出现的报错，随后更新了一下插件到1.5.1版，报错依旧
已经排查过的问题：API有效，对应OpenAI账户有效且有余额，代理设置正确，尝试清理插件对应config并重装插件后失败
未尝试过的操作：重启服务器

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-openai-plugin/issues/42

**Comment by Hammerstein3217** [comment]
您好，地鼠（刘航）已经收到你的邮件，正在查看
